// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: protos/jwgl.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求学期课表的信息
type GetSemesterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentID string `protobuf:"bytes,1,opt,name=studentID,proto3" json:"studentID,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Semester  string `protobuf:"bytes,3,opt,name=semester,proto3" json:"semester,omitempty"`
}

func (x *GetSemesterRequest) Reset() {
	*x = GetSemesterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_jwgl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSemesterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemesterRequest) ProtoMessage() {}

func (x *GetSemesterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwgl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemesterRequest.ProtoReflect.Descriptor instead.
func (*GetSemesterRequest) Descriptor() ([]byte, []int) {
	return file_protos_jwgl_proto_rawDescGZIP(), []int{0}
}

func (x *GetSemesterRequest) GetStudentID() string {
	if x != nil {
		return x.StudentID
	}
	return ""
}

func (x *GetSemesterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetSemesterRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

// 返回学期课表的信息
type GetSemesterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courses   []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	IcsStream []byte    `protobuf:"bytes,2,opt,name=icsStream,proto3" json:"icsStream,omitempty"`
}

func (x *GetSemesterResponse) Reset() {
	*x = GetSemesterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_jwgl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSemesterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemesterResponse) ProtoMessage() {}

func (x *GetSemesterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwgl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemesterResponse.ProtoReflect.Descriptor instead.
func (*GetSemesterResponse) Descriptor() ([]byte, []int) {
	return file_protos_jwgl_proto_rawDescGZIP(), []int{1}
}

func (x *GetSemesterResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *GetSemesterResponse) GetIcsStream() []byte {
	if x != nil {
		return x.IcsStream
	}
	return nil
}

// 课程信息
type Course struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Teacher         string  `protobuf:"bytes,2,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Place           string  `protobuf:"bytes,3,opt,name=place,proto3" json:"place,omitempty"`
	Weeks           []int32 `protobuf:"varint,4,rep,packed,name=weeks,proto3" json:"weeks,omitempty"`
	BeginTimeString string  `protobuf:"bytes,5,opt,name=beginTimeString,proto3" json:"beginTimeString,omitempty"`
	EndTimeString   string  `protobuf:"bytes,6,opt,name=endTimeString,proto3" json:"endTimeString,omitempty"`
	DayOfWeek       int32   `protobuf:"varint,7,opt,name=dayOfWeek,proto3" json:"dayOfWeek,omitempty"`
}

func (x *Course) Reset() {
	*x = Course{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_jwgl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwgl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_protos_jwgl_proto_rawDescGZIP(), []int{2}
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *Course) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *Course) GetWeeks() []int32 {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *Course) GetBeginTimeString() string {
	if x != nil {
		return x.BeginTimeString
	}
	return ""
}

func (x *Course) GetEndTimeString() string {
	if x != nil {
		return x.EndTimeString
	}
	return ""
}

func (x *Course) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

var File_protos_jwgl_proto protoreflect.FileDescriptor

var file_protos_jwgl_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6a, 0x77, 0x67, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6a, 0x77, 0x67, 0x6c, 0x22, 0x6a, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6d,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6a, 0x77, 0x67, 0x6c, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x63, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x63, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x22, 0xd0, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x65, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x79, 0x4f, 0x66,
	0x57, 0x65, 0x65, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x61, 0x79, 0x4f,
	0x66, 0x57, 0x65, 0x65, 0x6b, 0x32, 0x4c, 0x0a, 0x06, 0x4a, 0x77, 0x67, 0x6c, 0x65, 0x72, 0x12,
	0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18,
	0x2e, 0x6a, 0x77, 0x67, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6a, 0x77, 0x67, 0x6c, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa,
	0x02, 0x0c, 0x4a, 0x77, 0x67, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_jwgl_proto_rawDescOnce sync.Once
	file_protos_jwgl_proto_rawDescData = file_protos_jwgl_proto_rawDesc
)

func file_protos_jwgl_proto_rawDescGZIP() []byte {
	file_protos_jwgl_proto_rawDescOnce.Do(func() {
		file_protos_jwgl_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_jwgl_proto_rawDescData)
	})
	return file_protos_jwgl_proto_rawDescData
}

var file_protos_jwgl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_jwgl_proto_goTypes = []interface{}{
	(*GetSemesterRequest)(nil),  // 0: jwgl.GetSemesterRequest
	(*GetSemesterResponse)(nil), // 1: jwgl.GetSemesterResponse
	(*Course)(nil),              // 2: jwgl.Course
}
var file_protos_jwgl_proto_depIdxs = []int32{
	2, // 0: jwgl.GetSemesterResponse.courses:type_name -> jwgl.Course
	0, // 1: jwgl.Jwgler.GetSemester:input_type -> jwgl.GetSemesterRequest
	1, // 2: jwgl.Jwgler.GetSemester:output_type -> jwgl.GetSemesterResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_jwgl_proto_init() }
func file_protos_jwgl_proto_init() {
	if File_protos_jwgl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_jwgl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSemesterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_jwgl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSemesterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_jwgl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Course); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_jwgl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_jwgl_proto_goTypes,
		DependencyIndexes: file_protos_jwgl_proto_depIdxs,
		MessageInfos:      file_protos_jwgl_proto_msgTypes,
	}.Build()
	File_protos_jwgl_proto = out.File
	file_protos_jwgl_proto_rawDesc = nil
	file_protos_jwgl_proto_goTypes = nil
	file_protos_jwgl_proto_depIdxs = nil
}
